// 受験生に人気の参考書データ
// 偏差値帯/科目別の標準ルートで使われる代表書
// TODO: 実データに置き換え（書店APIや手動登録）

import type { GradeId } from "./curriculum";

export type Textbook = {
  id: string;
  name: string;
  publisher: string;
  subject: string; // category id from curriculum
  level: "basic" | "standard" | "advanced" | "top"; // 基礎/標準/応用/最難関
  forGrades: GradeId[];
  description: string;
  tags: string[];
};

export const TEXTBOOKS: Textbook[] = [
  // ── 数学 ──
  {
    id: "tb-math-yellow-chart",
    name: "黄チャート（数学I+A / II+B+C / III+C）",
    publisher: "数研出版",
    subject: "math",
    level: "standard",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "教科書〜共通テスト〜中堅大対応。例題網羅型の王道。",
    tags: ["網羅系", "例題"],
  },
  {
    id: "tb-math-blue-chart",
    name: "青チャート（数学I+A / II+B+C / III+C）",
    publisher: "数研出版",
    subject: "math",
    level: "advanced",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "難関大志望の定番。例題＋エクササイズで網羅。",
    tags: ["網羅系", "難関大"],
  },
  {
    id: "tb-math-focus-gold",
    name: "Focus Gold（数学）",
    publisher: "啓林館",
    subject: "math",
    level: "advanced",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "青チャ同等の網羅系。解説の質が高い。",
    tags: ["網羅系"],
  },
  {
    id: "tb-math-kihon-rensyu",
    name: "基礎問題精講（数学I+A/II+B+C/III+C）",
    publisher: "旺文社",
    subject: "math",
    level: "basic",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "基礎を素早く固めたい受験生に。1冊150題ほど。",
    tags: ["基礎", "薄め"],
  },
  {
    id: "tb-math-1aibun-jiritsu",
    name: "数学I+A/II+B+C 標準問題精講",
    publisher: "旺文社",
    subject: "math",
    level: "advanced",
    forGrades: ["h2", "h3", "ronin"],
    description: "難関大の標準問題に強い。基礎問の次に。",
    tags: ["難関大"],
  },
  {
    id: "tb-math-1taich",
    name: "1対1対応の演習（数学）",
    publisher: "東京出版",
    subject: "math",
    level: "advanced",
    forGrades: ["h2", "h3", "ronin"],
    description: "1問1問の質が高い。東大京大早慶志望に。",
    tags: ["1対1", "難関大"],
  },
  {
    id: "tb-math-yasashi-riko",
    name: "やさしい理系数学",
    publisher: "河合出版",
    subject: "math",
    level: "top",
    forGrades: ["h3", "ronin"],
    description: "タイトルに反し難しい。難関国公立医学部対応。",
    tags: ["最難関"],
  },
  {
    id: "tb-math-platinum",
    name: "数学プラチカ（I+A+II+B+C / III）",
    publisher: "河合出版",
    subject: "math",
    level: "advanced",
    forGrades: ["h3", "ronin"],
    description: "理系プラチカと文系プラチカ。良問演習。",
    tags: ["演習"],
  },
  // ── 英語 ──
  {
    id: "tb-eng-target1900",
    name: "英単語ターゲット1900",
    publisher: "旺文社",
    subject: "english",
    level: "standard",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "受験必須単語1900語。共通テスト〜難関大。",
    tags: ["単語"],
  },
  {
    id: "tb-eng-system",
    name: "システム英単語",
    publisher: "駿台文庫",
    subject: "english",
    level: "standard",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "ミニマルフレーズで覚える。シス単。",
    tags: ["単語"],
  },
  {
    id: "tb-eng-leap",
    name: "LEAP",
    publisher: "数研出版",
    subject: "english",
    level: "standard",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "意味だけでなく語法・コロケーションも学べる。",
    tags: ["単語"],
  },
  {
    id: "tb-eng-stock4500",
    name: "速読英熟語",
    publisher: "Z会",
    subject: "english",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "熟語＋長文で同時に鍛える。",
    tags: ["熟語"],
  },
  {
    id: "tb-eng-vintage",
    name: "Vintage",
    publisher: "いいずな書店",
    subject: "english",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "文法・語法・イディオム1冊網羅。",
    tags: ["文法"],
  },
  {
    id: "tb-eng-nextstage",
    name: "Next Stage（ネクステ）",
    publisher: "桐原書店",
    subject: "english",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "Vintage同等の網羅系。",
    tags: ["文法"],
  },
  {
    id: "tb-eng-polaris1",
    name: "英語長文ポラリス1（標準）",
    publisher: "KADOKAWA",
    subject: "english",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "関正生監修の長文。基礎〜標準。",
    tags: ["長文"],
  },
  {
    id: "tb-eng-polaris2",
    name: "英語長文ポラリス2（応用）",
    publisher: "KADOKAWA",
    subject: "english",
    level: "advanced",
    forGrades: ["h3", "ronin"],
    description: "MARCH〜早慶レベル。",
    tags: ["長文"],
  },
  {
    id: "tb-eng-yakkai",
    name: "やっておきたい英語長文300/500/700/1000",
    publisher: "河合出版",
    subject: "english",
    level: "advanced",
    forGrades: ["h2", "h3", "ronin"],
    description: "語数別シリーズ。難関大対策に。",
    tags: ["長文"],
  },
  {
    id: "tb-eng-toudai-eigo25",
    name: "東大の英語25カ年",
    publisher: "教学社",
    subject: "english",
    level: "top",
    forGrades: ["h3", "ronin"],
    description: "東大過去問。最難関対策。",
    tags: ["過去問", "最難関"],
  },
  // ── 国語 ──
  {
    id: "tb-jp-genbun-akahon",
    name: "現代文 入試問題集",
    publisher: "河合出版",
    subject: "japanese",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "演習形式の現代文。",
    tags: ["現代文"],
  },
  {
    id: "tb-jp-kobun-tango",
    name: "古文単語ゴロゴ",
    publisher: "スタディカンパニー",
    subject: "japanese",
    level: "basic",
    forGrades: ["h1", "h2", "h3", "ronin"],
    description: "ゴロで覚える古文単語565。",
    tags: ["古文", "単語"],
  },
  {
    id: "tb-jp-kobun-step",
    name: "ステップアップ古文",
    publisher: "数研出版",
    subject: "japanese",
    level: "basic",
    forGrades: ["h1", "h2"],
    description: "古典文法の基礎を段階的に。",
    tags: ["古文", "文法"],
  },
  {
    id: "tb-jp-kanbun-soku",
    name: "漢文早覚え速答法",
    publisher: "学研プラス",
    subject: "japanese",
    level: "basic",
    forGrades: ["h2", "h3", "ronin"],
    description: "漢文句法を素早くマスター。",
    tags: ["漢文"],
  },
  // ── 物理 ──
  {
    id: "tb-phy-rejireji",
    name: "物理のエッセンス（力学・波動 / 熱・電磁気・原子）",
    publisher: "河合出版",
    subject: "science",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "物理の基礎を体系的に。",
    tags: ["物理", "基礎"],
  },
  {
    id: "tb-phy-meikai-meirou",
    name: "物理 良問の風 / 名問の森",
    publisher: "河合出版",
    subject: "science",
    level: "advanced",
    forGrades: ["h2", "h3", "ronin"],
    description: "エッセンスの次。中堅〜難関大対応。",
    tags: ["物理", "演習"],
  },
  // ── 化学 ──
  {
    id: "tb-chem-doujou",
    name: "化学（理論・無機・有機）の新研究",
    publisher: "三省堂",
    subject: "science",
    level: "advanced",
    forGrades: ["h2", "h3", "ronin"],
    description: "辞書的に使える化学参考書。",
    tags: ["化学", "参考書"],
  },
  {
    id: "tb-chem-shinshugo",
    name: "化学 重要問題集",
    publisher: "数研出版",
    subject: "science",
    level: "advanced",
    forGrades: ["h2", "h3", "ronin"],
    description: "全国の化学入試問題網羅。",
    tags: ["化学", "演習"],
  },
  // ── 生物 ──
  {
    id: "tb-bio-omoroi",
    name: "大森徹の生物 記述・論述問題の解法",
    publisher: "旺文社",
    subject: "science",
    level: "advanced",
    forGrades: ["h3", "ronin"],
    description: "生物論述対策の定番。",
    tags: ["生物"],
  },
  // ── 社会 ──
  {
    id: "tb-soc-yamakawa-jp",
    name: "詳説日本史B（山川出版）",
    publisher: "山川出版社",
    subject: "social",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "教科書の決定版。",
    tags: ["日本史"],
  },
  {
    id: "tb-soc-yamakawa-world",
    name: "詳説世界史B（山川出版）",
    publisher: "山川出版社",
    subject: "social",
    level: "standard",
    forGrades: ["h2", "h3", "ronin"],
    description: "教科書の決定版。",
    tags: ["世界史"],
  },
  {
    id: "tb-soc-ichikawa-pol",
    name: "畠山のスパッとわかる政治・経済 爽快講義",
    publisher: "栄光",
    subject: "social",
    level: "standard",
    forGrades: ["h3", "ronin"],
    description: "政経の決定版講義書。",
    tags: ["政治経済"],
  },
];

export const TEXTBOOK_TAGS = [
  "網羅系",
  "基礎",
  "演習",
  "難関大",
  "最難関",
  "単語",
  "文法",
  "長文",
  "古文",
  "漢文",
  "物理",
  "化学",
  "生物",
  "日本史",
  "世界史",
  "政治経済",
  "1対1",
  "過去問",
] as const;

export function searchTextbooks(query: string): Textbook[] {
  const q = query.trim().toLowerCase();
  if (!q) return TEXTBOOKS;
  return TEXTBOOKS.filter((t) => {
    const haystack = `${t.name} ${t.publisher} ${t.description} ${t.tags.join(" ")}`.toLowerCase();
    return haystack.includes(q);
  });
}
