// 主要日本の大学・学部データ
// 偏差値は河合塾・駿台などの公開データを参考にした概算（2024-2025年度ベース）
// TODO: 実データに置き換え（公式ソースから取得、または管理画面で編集可能に）

export type FacultyCategory =
  | "letters" // 文学・人文・教育
  | "law" // 法
  | "economics" // 経済・経営・商
  | "social" // 社会・国際・政策
  | "science" // 理
  | "engineering" // 工
  | "medical" // 医・歯・薬・看護
  | "agriculture" // 農・生物
  | "info" // 情報・データサイエンス
  | "art" // 芸術・スポーツ
  | "general"; // その他・総合

export type Faculty = {
  name: string;
  category: FacultyCategory;
  deviation: number; // 偏差値の中央値
};

export type University = {
  id: string;
  name: string;
  shortName?: string;
  type: "national" | "public" | "private";
  region: string;
  tier: "S" | "A" | "B" | "C" | "D"; // S:最難関 A:難関 B:準難関 C:中堅 D:一般
  faculties: Faculty[];
};

export const FACULTY_CATEGORY_LABEL: Record<FacultyCategory, string> = {
  letters: "文学・人文・教育",
  law: "法",
  economics: "経済・経営・商",
  social: "社会・国際・政策",
  science: "理学",
  engineering: "工学",
  medical: "医療・薬学・看護",
  agriculture: "農・生命科学",
  info: "情報・データ",
  art: "芸術・スポーツ",
  general: "総合・その他",
};

export const UNIVERSITIES: University[] = [
  // ─── 最難関 国公立 ───
  {
    id: "u-tokyo",
    name: "東京大学",
    shortName: "東大",
    type: "national",
    region: "関東",
    tier: "S",
    faculties: [
      { name: "文科一類", category: "law", deviation: 70 },
      { name: "文科二類", category: "economics", deviation: 69 },
      { name: "文科三類", category: "letters", deviation: 68 },
      { name: "理科一類", category: "engineering", deviation: 68 },
      { name: "理科二類", category: "agriculture", deviation: 67 },
      { name: "理科三類", category: "medical", deviation: 75 },
    ],
  },
  {
    id: "u-kyoto",
    name: "京都大学",
    shortName: "京大",
    type: "national",
    region: "関西",
    tier: "S",
    faculties: [
      { name: "総合人間", category: "general", deviation: 67 },
      { name: "文", category: "letters", deviation: 66 },
      { name: "教育", category: "letters", deviation: 65 },
      { name: "法", category: "law", deviation: 67 },
      { name: "経済", category: "economics", deviation: 66 },
      { name: "理", category: "science", deviation: 65 },
      { name: "医", category: "medical", deviation: 72 },
      { name: "薬", category: "medical", deviation: 65 },
      { name: "工", category: "engineering", deviation: 65 },
      { name: "農", category: "agriculture", deviation: 63 },
    ],
  },
  {
    id: "hitotsubashi",
    name: "一橋大学",
    type: "national",
    region: "関東",
    tier: "S",
    faculties: [
      { name: "商", category: "economics", deviation: 67 },
      { name: "経済", category: "economics", deviation: 67 },
      { name: "法", category: "law", deviation: 67 },
      { name: "社会", category: "social", deviation: 67 },
      { name: "ソーシャル・データサイエンス", category: "info", deviation: 66 },
    ],
  },
  {
    id: "tokyo-tech",
    name: "東京科学大学（旧東工大）",
    shortName: "科学大",
    type: "national",
    region: "関東",
    tier: "S",
    faculties: [
      { name: "理学院", category: "science", deviation: 65 },
      { name: "工学院", category: "engineering", deviation: 65 },
      { name: "物質理工学院", category: "engineering", deviation: 64 },
      { name: "情報理工学院", category: "info", deviation: 66 },
      { name: "生命理工学院", category: "agriculture", deviation: 63 },
      { name: "環境・社会理工学院", category: "engineering", deviation: 63 },
    ],
  },
  // ─── 旧帝大 ───
  {
    id: "u-osaka",
    name: "大阪大学",
    shortName: "阪大",
    type: "national",
    region: "関西",
    tier: "S",
    faculties: [
      { name: "文", category: "letters", deviation: 63 },
      { name: "人間科学", category: "social", deviation: 64 },
      { name: "外国語", category: "letters", deviation: 60 },
      { name: "法", category: "law", deviation: 64 },
      { name: "経済", category: "economics", deviation: 64 },
      { name: "理", category: "science", deviation: 62 },
      { name: "工", category: "engineering", deviation: 62 },
      { name: "基礎工", category: "engineering", deviation: 61 },
      { name: "医", category: "medical", deviation: 71 },
      { name: "薬", category: "medical", deviation: 63 },
      { name: "歯", category: "medical", deviation: 60 },
    ],
  },
  {
    id: "u-nagoya",
    name: "名古屋大学",
    shortName: "名大",
    type: "national",
    region: "中部",
    tier: "A",
    faculties: [
      { name: "文", category: "letters", deviation: 61 },
      { name: "教育", category: "letters", deviation: 60 },
      { name: "法", category: "law", deviation: 62 },
      { name: "経済", category: "economics", deviation: 62 },
      { name: "情報", category: "info", deviation: 62 },
      { name: "理", category: "science", deviation: 60 },
      { name: "工", category: "engineering", deviation: 60 },
      { name: "医", category: "medical", deviation: 70 },
      { name: "農", category: "agriculture", deviation: 59 },
    ],
  },
  {
    id: "u-tohoku",
    name: "東北大学",
    type: "national",
    region: "東北",
    tier: "A",
    faculties: [
      { name: "文", category: "letters", deviation: 60 },
      { name: "教育", category: "letters", deviation: 60 },
      { name: "法", category: "law", deviation: 61 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "理", category: "science", deviation: 59 },
      { name: "工", category: "engineering", deviation: 59 },
      { name: "医", category: "medical", deviation: 69 },
      { name: "薬", category: "medical", deviation: 62 },
      { name: "農", category: "agriculture", deviation: 58 },
    ],
  },
  {
    id: "u-hokkaido",
    name: "北海道大学",
    shortName: "北大",
    type: "national",
    region: "北海道",
    tier: "A",
    faculties: [
      { name: "文", category: "letters", deviation: 59 },
      { name: "教育", category: "letters", deviation: 59 },
      { name: "法", category: "law", deviation: 60 },
      { name: "経済", category: "economics", deviation: 59 },
      { name: "理", category: "science", deviation: 58 },
      { name: "工", category: "engineering", deviation: 58 },
      { name: "医", category: "medical", deviation: 68 },
      { name: "歯", category: "medical", deviation: 57 },
      { name: "薬", category: "medical", deviation: 62 },
      { name: "農", category: "agriculture", deviation: 58 },
      { name: "獣医", category: "agriculture", deviation: 62 },
    ],
  },
  {
    id: "u-kyushu",
    name: "九州大学",
    shortName: "九大",
    type: "national",
    region: "九州",
    tier: "A",
    faculties: [
      { name: "文", category: "letters", deviation: 60 },
      { name: "教育", category: "letters", deviation: 60 },
      { name: "法", category: "law", deviation: 60 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "共創", category: "general", deviation: 60 },
      { name: "理", category: "science", deviation: 58 },
      { name: "工", category: "engineering", deviation: 58 },
      { name: "医", category: "medical", deviation: 69 },
      { name: "薬", category: "medical", deviation: 62 },
      { name: "農", category: "agriculture", deviation: 58 },
    ],
  },
  // ─── 国公立準難関 ───
  {
    id: "u-kobe",
    name: "神戸大学",
    type: "national",
    region: "関西",
    tier: "A",
    faculties: [
      { name: "文", category: "letters", deviation: 61 },
      { name: "国際人間科学", category: "social", deviation: 61 },
      { name: "法", category: "law", deviation: 62 },
      { name: "経済", category: "economics", deviation: 62 },
      { name: "経営", category: "economics", deviation: 63 },
      { name: "理", category: "science", deviation: 58 },
      { name: "工", category: "engineering", deviation: 58 },
      { name: "農", category: "agriculture", deviation: 58 },
      { name: "医", category: "medical", deviation: 68 },
    ],
  },
  {
    id: "tsukuba",
    name: "筑波大学",
    type: "national",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "人文・文化", category: "letters", deviation: 60 },
      { name: "社会・国際", category: "social", deviation: 62 },
      { name: "人間", category: "letters", deviation: 60 },
      { name: "生命環境", category: "agriculture", deviation: 58 },
      { name: "理工", category: "engineering", deviation: 60 },
      { name: "情報", category: "info", deviation: 62 },
      { name: "医", category: "medical", deviation: 67 },
      { name: "体育専門", category: "art", deviation: 56 },
      { name: "芸術専門", category: "art", deviation: 56 },
    ],
  },
  {
    id: "yokohama-national",
    name: "横浜国立大学",
    shortName: "横国",
    type: "national",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "教育", category: "letters", deviation: 56 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "経営", category: "economics", deviation: 60 },
      { name: "理工", category: "engineering", deviation: 58 },
      { name: "都市科学", category: "engineering", deviation: 58 },
    ],
  },
  {
    id: "tokyo-u-foreign",
    name: "東京外国語大学",
    type: "national",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "言語文化", category: "letters", deviation: 62 },
      { name: "国際社会", category: "social", deviation: 62 },
      { name: "国際日本", category: "social", deviation: 60 },
    ],
  },
  {
    id: "ochanomizu",
    name: "お茶の水女子大学",
    type: "national",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "文教育", category: "letters", deviation: 60 },
      { name: "理", category: "science", deviation: 58 },
      { name: "生活科学", category: "agriculture", deviation: 58 },
      { name: "共創工", category: "engineering", deviation: 58 },
    ],
  },
  // ─── 早慶上理ICU ───
  {
    id: "waseda",
    name: "早稲田大学",
    shortName: "早稲田",
    type: "private",
    region: "関東",
    tier: "S",
    faculties: [
      { name: "政治経済", category: "economics", deviation: 70 },
      { name: "法", category: "law", deviation: 68 },
      { name: "商", category: "economics", deviation: 68 },
      { name: "文", category: "letters", deviation: 67 },
      { name: "文化構想", category: "letters", deviation: 67 },
      { name: "教育", category: "letters", deviation: 65 },
      { name: "社会科学", category: "social", deviation: 68 },
      { name: "国際教養", category: "social", deviation: 68 },
      { name: "人間科学", category: "social", deviation: 64 },
      { name: "スポーツ科学", category: "art", deviation: 62 },
      { name: "基幹理工", category: "engineering", deviation: 65 },
      { name: "創造理工", category: "engineering", deviation: 64 },
      { name: "先進理工", category: "science", deviation: 65 },
    ],
  },
  {
    id: "keio",
    name: "慶應義塾大学",
    shortName: "慶應",
    type: "private",
    region: "関東",
    tier: "S",
    faculties: [
      { name: "文", category: "letters", deviation: 66 },
      { name: "経済", category: "economics", deviation: 68 },
      { name: "法", category: "law", deviation: 68 },
      { name: "商", category: "economics", deviation: 66 },
      { name: "医", category: "medical", deviation: 73 },
      { name: "理工", category: "engineering", deviation: 65 },
      { name: "総合政策", category: "social", deviation: 66 },
      { name: "環境情報", category: "info", deviation: 66 },
      { name: "看護医療", category: "medical", deviation: 58 },
      { name: "薬", category: "medical", deviation: 63 },
    ],
  },
  {
    id: "sophia",
    name: "上智大学",
    type: "private",
    region: "関東",
    tier: "A",
    faculties: [
      { name: "神", category: "letters", deviation: 60 },
      { name: "文", category: "letters", deviation: 63 },
      { name: "総合人間科学", category: "social", deviation: 62 },
      { name: "法", category: "law", deviation: 64 },
      { name: "経済", category: "economics", deviation: 63 },
      { name: "外国語", category: "letters", deviation: 64 },
      { name: "総合グローバル", category: "social", deviation: 64 },
      { name: "理工", category: "engineering", deviation: 60 },
    ],
  },
  {
    id: "tokyo-rika",
    name: "東京理科大学",
    shortName: "理科大",
    type: "private",
    region: "関東",
    tier: "A",
    faculties: [
      { name: "理", category: "science", deviation: 61 },
      { name: "工", category: "engineering", deviation: 60 },
      { name: "創域理工", category: "engineering", deviation: 58 },
      { name: "先進工", category: "engineering", deviation: 60 },
      { name: "薬", category: "medical", deviation: 62 },
      { name: "経営", category: "economics", deviation: 58 },
    ],
  },
  {
    id: "icu",
    name: "国際基督教大学",
    shortName: "ICU",
    type: "private",
    region: "関東",
    tier: "A",
    faculties: [
      { name: "教養", category: "social", deviation: 65 },
    ],
  },
  // ─── MARCH ───
  {
    id: "meiji",
    name: "明治大学",
    type: "private",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "法", category: "law", deviation: 62 },
      { name: "商", category: "economics", deviation: 62 },
      { name: "政治経済", category: "economics", deviation: 63 },
      { name: "文", category: "letters", deviation: 62 },
      { name: "経営", category: "economics", deviation: 62 },
      { name: "情報コミュニケーション", category: "info", deviation: 62 },
      { name: "国際日本", category: "social", deviation: 62 },
      { name: "理工", category: "engineering", deviation: 60 },
      { name: "農", category: "agriculture", deviation: 60 },
      { name: "総合数理", category: "info", deviation: 59 },
    ],
  },
  {
    id: "aoyama",
    name: "青山学院大学",
    shortName: "青学",
    type: "private",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "文", category: "letters", deviation: 62 },
      { name: "教育人間科学", category: "letters", deviation: 60 },
      { name: "経済", category: "economics", deviation: 62 },
      { name: "法", category: "law", deviation: 62 },
      { name: "経営", category: "economics", deviation: 63 },
      { name: "国際政治経済", category: "social", deviation: 65 },
      { name: "総合文化政策", category: "social", deviation: 63 },
      { name: "理工", category: "engineering", deviation: 58 },
      { name: "社会情報", category: "info", deviation: 60 },
      { name: "地球社会共生", category: "social", deviation: 60 },
      { name: "コミュニティ人間科学", category: "social", deviation: 58 },
    ],
  },
  {
    id: "rikkyo",
    name: "立教大学",
    type: "private",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "文", category: "letters", deviation: 62 },
      { name: "異文化コミュニケーション", category: "letters", deviation: 65 },
      { name: "経済", category: "economics", deviation: 62 },
      { name: "経営", category: "economics", deviation: 65 },
      { name: "理", category: "science", deviation: 58 },
      { name: "社会", category: "social", deviation: 62 },
      { name: "法", category: "law", deviation: 62 },
      { name: "観光", category: "social", deviation: 60 },
      { name: "コミュニティ福祉", category: "social", deviation: 58 },
      { name: "現代心理", category: "social", deviation: 60 },
      { name: "スポーツウエルネス", category: "art", deviation: 58 },
      { name: "Global Liberal Arts Program", category: "social", deviation: 65 },
    ],
  },
  {
    id: "chuo",
    name: "中央大学",
    type: "private",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "法", category: "law", deviation: 62 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "商", category: "economics", deviation: 60 },
      { name: "文", category: "letters", deviation: 60 },
      { name: "総合政策", category: "social", deviation: 60 },
      { name: "国際経営", category: "economics", deviation: 60 },
      { name: "国際情報", category: "info", deviation: 60 },
      { name: "理工", category: "engineering", deviation: 58 },
    ],
  },
  {
    id: "hosei",
    name: "法政大学",
    type: "private",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "法", category: "law", deviation: 60 },
      { name: "文", category: "letters", deviation: 60 },
      { name: "経済", category: "economics", deviation: 58 },
      { name: "経営", category: "economics", deviation: 60 },
      { name: "国際文化", category: "letters", deviation: 60 },
      { name: "人間環境", category: "social", deviation: 58 },
      { name: "現代福祉", category: "social", deviation: 56 },
      { name: "キャリアデザイン", category: "social", deviation: 58 },
      { name: "GIS", category: "social", deviation: 60 },
      { name: "スポーツ健康", category: "art", deviation: 56 },
      { name: "情報科学", category: "info", deviation: 56 },
      { name: "デザイン工", category: "engineering", deviation: 56 },
      { name: "理工", category: "engineering", deviation: 56 },
      { name: "生命科学", category: "agriculture", deviation: 56 },
      { name: "社会", category: "social", deviation: 58 },
    ],
  },
  // ─── 関関同立 ───
  {
    id: "kansai",
    name: "関西大学",
    type: "private",
    region: "関西",
    tier: "B",
    faculties: [
      { name: "法", category: "law", deviation: 58 },
      { name: "文", category: "letters", deviation: 58 },
      { name: "経済", category: "economics", deviation: 58 },
      { name: "商", category: "economics", deviation: 60 },
      { name: "社会", category: "social", deviation: 60 },
      { name: "政策創造", category: "social", deviation: 58 },
      { name: "外国語", category: "letters", deviation: 60 },
      { name: "人間健康", category: "social", deviation: 56 },
      { name: "総合情報", category: "info", deviation: 58 },
      { name: "社会安全", category: "social", deviation: 56 },
      { name: "システム理工", category: "engineering", deviation: 56 },
      { name: "環境都市工", category: "engineering", deviation: 56 },
      { name: "化学生命工", category: "engineering", deviation: 56 },
    ],
  },
  {
    id: "kwansei",
    name: "関西学院大学",
    shortName: "関学",
    type: "private",
    region: "関西",
    tier: "B",
    faculties: [
      { name: "神", category: "letters", deviation: 55 },
      { name: "文", category: "letters", deviation: 60 },
      { name: "社会", category: "social", deviation: 60 },
      { name: "法", category: "law", deviation: 60 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "商", category: "economics", deviation: 60 },
      { name: "人間福祉", category: "social", deviation: 58 },
      { name: "国際", category: "social", deviation: 65 },
      { name: "教育", category: "letters", deviation: 58 },
      { name: "総合政策", category: "social", deviation: 58 },
      { name: "理", category: "science", deviation: 56 },
      { name: "工", category: "engineering", deviation: 56 },
      { name: "生命環境", category: "agriculture", deviation: 56 },
      { name: "建築", category: "engineering", deviation: 56 },
    ],
  },
  {
    id: "doshisha",
    name: "同志社大学",
    type: "private",
    region: "関西",
    tier: "B",
    faculties: [
      { name: "神", category: "letters", deviation: 58 },
      { name: "文", category: "letters", deviation: 60 },
      { name: "社会", category: "social", deviation: 60 },
      { name: "法", category: "law", deviation: 62 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "商", category: "economics", deviation: 60 },
      { name: "政策", category: "social", deviation: 60 },
      { name: "文化情報", category: "info", deviation: 58 },
      { name: "理工", category: "engineering", deviation: 60 },
      { name: "生命医科学", category: "medical", deviation: 58 },
      { name: "スポーツ健康", category: "art", deviation: 56 },
      { name: "心理", category: "social", deviation: 62 },
      { name: "グローバル・コミュニケーション", category: "social", deviation: 63 },
      { name: "グローバル地域文化", category: "social", deviation: 62 },
    ],
  },
  {
    id: "ritsumeikan",
    name: "立命館大学",
    type: "private",
    region: "関西",
    tier: "B",
    faculties: [
      { name: "法", category: "law", deviation: 60 },
      { name: "文", category: "letters", deviation: 58 },
      { name: "産業社会", category: "social", deviation: 58 },
      { name: "国際関係", category: "social", deviation: 62 },
      { name: "経済", category: "economics", deviation: 58 },
      { name: "経営", category: "economics", deviation: 60 },
      { name: "政策科学", category: "social", deviation: 58 },
      { name: "総合心理", category: "social", deviation: 60 },
      { name: "映像", category: "art", deviation: 58 },
      { name: "理工", category: "engineering", deviation: 56 },
      { name: "情報理工", category: "info", deviation: 58 },
      { name: "生命科学", category: "agriculture", deviation: 58 },
      { name: "薬", category: "medical", deviation: 60 },
      { name: "スポーツ健康科学", category: "art", deviation: 56 },
      { name: "食マネジメント", category: "agriculture", deviation: 56 },
      { name: "グローバル教養", category: "social", deviation: 62 },
    ],
  },
  // ─── 日東駒専 ───
  {
    id: "nihon",
    name: "日本大学",
    shortName: "日大",
    type: "private",
    region: "関東",
    tier: "C",
    faculties: [
      { name: "法", category: "law", deviation: 55 },
      { name: "文理", category: "letters", deviation: 55 },
      { name: "経済", category: "economics", deviation: 55 },
      { name: "商", category: "economics", deviation: 55 },
      { name: "芸術", category: "art", deviation: 55 },
      { name: "国際関係", category: "social", deviation: 54 },
      { name: "理工", category: "engineering", deviation: 52 },
      { name: "生産工", category: "engineering", deviation: 50 },
      { name: "工", category: "engineering", deviation: 48 },
      { name: "医", category: "medical", deviation: 65 },
      { name: "歯", category: "medical", deviation: 54 },
      { name: "松戸歯", category: "medical", deviation: 52 },
      { name: "薬", category: "medical", deviation: 56 },
      { name: "生物資源科学", category: "agriculture", deviation: 54 },
      { name: "危機管理", category: "social", deviation: 50 },
      { name: "スポーツ科学", category: "art", deviation: 50 },
    ],
  },
  {
    id: "toyo",
    name: "東洋大学",
    type: "private",
    region: "関東",
    tier: "C",
    faculties: [
      { name: "文", category: "letters", deviation: 55 },
      { name: "経済", category: "economics", deviation: 56 },
      { name: "経営", category: "economics", deviation: 55 },
      { name: "法", category: "law", deviation: 55 },
      { name: "社会", category: "social", deviation: 55 },
      { name: "国際", category: "social", deviation: 58 },
      { name: "国際観光", category: "social", deviation: 58 },
      { name: "情報連携", category: "info", deviation: 55 },
      { name: "ライフデザイン", category: "social", deviation: 53 },
      { name: "理工", category: "engineering", deviation: 50 },
      { name: "総合情報", category: "info", deviation: 53 },
      { name: "生命科学", category: "agriculture", deviation: 53 },
      { name: "食環境科学", category: "agriculture", deviation: 53 },
      { name: "福祉社会デザイン", category: "social", deviation: 53 },
      { name: "健康スポーツ科学", category: "art", deviation: 50 },
    ],
  },
  {
    id: "komazawa",
    name: "駒澤大学",
    type: "private",
    region: "関東",
    tier: "C",
    faculties: [
      { name: "仏教", category: "letters", deviation: 50 },
      { name: "文", category: "letters", deviation: 55 },
      { name: "経済", category: "economics", deviation: 55 },
      { name: "法", category: "law", deviation: 55 },
      { name: "経営", category: "economics", deviation: 55 },
      { name: "医療健康科学", category: "medical", deviation: 50 },
      { name: "グローバル・メディア・スタディーズ", category: "info", deviation: 55 },
    ],
  },
  {
    id: "senshu",
    name: "専修大学",
    type: "private",
    region: "関東",
    tier: "C",
    faculties: [
      { name: "経済", category: "economics", deviation: 53 },
      { name: "法", category: "law", deviation: 55 },
      { name: "経営", category: "economics", deviation: 53 },
      { name: "商", category: "economics", deviation: 53 },
      { name: "文", category: "letters", deviation: 55 },
      { name: "人間科学", category: "social", deviation: 53 },
      { name: "国際コミュニケーション", category: "social", deviation: 53 },
      { name: "ネットワーク情報", category: "info", deviation: 50 },
    ],
  },
  // ─── 産近甲龍 ───
  {
    id: "kyoto-sangyo",
    name: "京都産業大学",
    type: "private",
    region: "関西",
    tier: "C",
    faculties: [
      { name: "経済", category: "economics", deviation: 53 },
      { name: "経営", category: "economics", deviation: 53 },
      { name: "法", category: "law", deviation: 53 },
      { name: "現代社会", category: "social", deviation: 53 },
      { name: "国際関係", category: "social", deviation: 55 },
      { name: "外国語", category: "letters", deviation: 53 },
      { name: "文化", category: "letters", deviation: 53 },
      { name: "理", category: "science", deviation: 50 },
      { name: "情報理工", category: "info", deviation: 50 },
      { name: "生命科学", category: "agriculture", deviation: 50 },
    ],
  },
  {
    id: "kinki",
    name: "近畿大学",
    shortName: "近大",
    type: "private",
    region: "関西",
    tier: "C",
    faculties: [
      { name: "法", category: "law", deviation: 55 },
      { name: "経済", category: "economics", deviation: 55 },
      { name: "経営", category: "economics", deviation: 55 },
      { name: "理工", category: "engineering", deviation: 52 },
      { name: "建築", category: "engineering", deviation: 53 },
      { name: "薬", category: "medical", deviation: 55 },
      { name: "文芸", category: "letters", deviation: 55 },
      { name: "総合社会", category: "social", deviation: 55 },
      { name: "国際", category: "social", deviation: 58 },
      { name: "農", category: "agriculture", deviation: 53 },
      { name: "医", category: "medical", deviation: 65 },
      { name: "情報", category: "info", deviation: 53 },
      { name: "工", category: "engineering", deviation: 50 },
      { name: "産業理工", category: "engineering", deviation: 47 },
      { name: "生物理工", category: "agriculture", deviation: 47 },
    ],
  },
  // ─── その他人気・地方 ───
  {
    id: "gakushuin",
    name: "学習院大学",
    type: "private",
    region: "関東",
    tier: "B",
    faculties: [
      { name: "法", category: "law", deviation: 60 },
      { name: "経済", category: "economics", deviation: 60 },
      { name: "文", category: "letters", deviation: 60 },
      { name: "理", category: "science", deviation: 56 },
      { name: "国際社会科学", category: "social", deviation: 60 },
    ],
  },
  {
    id: "seikei",
    name: "成蹊大学",
    type: "private",
    region: "関東",
    tier: "C",
    faculties: [
      { name: "経済", category: "economics", deviation: 58 },
      { name: "経営", category: "economics", deviation: 58 },
      { name: "法", category: "law", deviation: 58 },
      { name: "文", category: "letters", deviation: 58 },
      { name: "理工", category: "engineering", deviation: 53 },
    ],
  },
  {
    id: "seijo",
    name: "成城大学",
    type: "private",
    region: "関東",
    tier: "C",
    faculties: [
      { name: "経済", category: "economics", deviation: 58 },
      { name: "文芸", category: "letters", deviation: 58 },
      { name: "法", category: "law", deviation: 58 },
      { name: "社会イノベーション", category: "social", deviation: 58 },
    ],
  },
];

export const TIER_LABEL: Record<University["tier"], string> = {
  S: "最難関",
  A: "難関",
  B: "準難関",
  C: "中堅",
  D: "一般",
};

export const REGIONS = [
  "北海道",
  "東北",
  "関東",
  "中部",
  "関西",
  "中国",
  "四国",
  "九州",
] as const;

export function findUniversity(id: string): University | undefined {
  return UNIVERSITIES.find((u) => u.id === id);
}

export function findFaculty(
  universityId: string,
  facultyName: string,
): Faculty | undefined {
  return findUniversity(universityId)?.faculties.find(
    (f) => f.name === facultyName,
  );
}

export function searchUniversities(query: string): University[] {
  const q = query.trim().toLowerCase();
  if (!q) return UNIVERSITIES;
  return UNIVERSITIES.filter((u) => {
    const haystack = `${u.name} ${u.shortName ?? ""} ${u.region}`.toLowerCase();
    return haystack.includes(q);
  });
}
