// 模試DB初期シード
// 河合塾・駿台・東進・代ゼミ・ベネッセ・進研模試の主要模試
// 公式URLは年度ごとに変わるため、最新年度のシリーズトップを指す
// TODO: 年度更新時に exam_date / deadline / official_url を最新化

import type { MockExam } from "../types";
import { buildSearchText } from "../types";

type Seed = Omit<MockExam, "searchText" | "source"> & {
  source?: MockExam["source"];
};

const CURRENT_YEAR = 2025;

const RAW: Seed[] = [
  // ─── 河合塾 ───
  {
    id: "me-kawai-zenkoku-1",
    provider: "kawai",
    name: "全統共通テスト模試 第1回",
    kana: "ぜんとうきょうつうてすともしだいいっかい",
    aliases: ["全統共テ", "河合全統"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-05-25`,
    deadline: `${CURRENT_YEAR}-05-12`,
    targetGrades: ["h3", "ronin"],
    format: "common-test-trial",
    officialUrl: "https://www.kawai-juku.ac.jp/zento/",
  },
  {
    id: "me-kawai-zenkoku-2",
    provider: "kawai",
    name: "全統共通テスト模試 第2回",
    kana: "ぜんとうきょうつうてすともしだいにかい",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-08-31`,
    targetGrades: ["h3", "ronin"],
    format: "common-test-trial",
    officialUrl: "https://www.kawai-juku.ac.jp/zento/",
  },
  {
    id: "me-kawai-kijutsu-1",
    provider: "kawai",
    name: "全統記述模試 第1回",
    kana: "ぜんとうきじゅつもしだいいっかい",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-06-15`,
    targetGrades: ["h3", "ronin"],
    format: "descriptive",
    officialUrl: "https://www.kawai-juku.ac.jp/zento/",
  },
  {
    id: "me-kawai-kijutsu-2",
    provider: "kawai",
    name: "全統記述模試 第2回",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-10-12`,
    targetGrades: ["h3", "ronin"],
    format: "descriptive",
    officialUrl: "https://www.kawai-juku.ac.jp/zento/",
  },
  {
    id: "me-kawai-todai",
    provider: "kawai",
    name: "東大入試オープン",
    kana: "とうだいにゅうしおーぷん",
    aliases: ["東大オープン"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-08-09`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-tokyo"],
    officialUrl: "https://www.kawai-juku.ac.jp/daigakubetsu/",
  },
  {
    id: "me-kawai-kyodai",
    provider: "kawai",
    name: "京大入試オープン",
    kana: "きょうだいにゅうしおーぷん",
    aliases: ["京大オープン"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-08-09`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-kyoto"],
    officialUrl: "https://www.kawai-juku.ac.jp/daigakubetsu/",
  },
  {
    id: "me-kawai-todai-2",
    provider: "kawai",
    name: "第2回 東大入試オープン",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-11-15`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-tokyo"],
    officialUrl: "https://www.kawai-juku.ac.jp/daigakubetsu/",
  },
  {
    id: "me-kawai-prov-1",
    provider: "kawai",
    name: "プライム模試 第1回（高1）",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-13`,
    targetGrades: ["h1"],
    format: "mark-descriptive",
  },
  {
    id: "me-kawai-prov-2",
    provider: "kawai",
    name: "全統高2模試",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-20`,
    targetGrades: ["h2"],
    format: "mark-descriptive",
  },

  // ─── 駿台 ───
  {
    id: "me-sundai-zenkoku-1",
    provider: "sundai",
    name: "駿台全国模試 第1回",
    kana: "すんだいぜんこくもしだいいっかい",
    aliases: ["駿台全国"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-05-25`,
    targetGrades: ["h3", "ronin"],
    format: "descriptive",
    officialUrl: "https://www2.sundai.ac.jp/moshi/",
    notes: "難度高め。難関大志望者向け",
  },
  {
    id: "me-sundai-zenkoku-2",
    provider: "sundai",
    name: "駿台全国模試 第2回",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-09-21`,
    targetGrades: ["h3", "ronin"],
    format: "descriptive",
    officialUrl: "https://www2.sundai.ac.jp/moshi/",
  },
  {
    id: "me-sundai-kyotsu-1",
    provider: "sundai",
    name: "駿台atama+共通テスト模試 第1回",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-06-08`,
    targetGrades: ["h3", "ronin"],
    format: "common-test-trial",
    officialUrl: "https://www2.sundai.ac.jp/moshi/",
  },
  {
    id: "me-sundai-todai-1",
    provider: "sundai",
    name: "東大入試実戦模試 第1回",
    kana: "とうだいにゅうしじっせんもし",
    aliases: ["駿台東大実戦"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-08-16`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-tokyo"],
    officialUrl: "https://www2.sundai.ac.jp/moshi/",
  },
  {
    id: "me-sundai-kyodai-1",
    provider: "sundai",
    name: "京大入試実戦模試 第1回",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-08-23`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-kyoto"],
    officialUrl: "https://www2.sundai.ac.jp/moshi/",
  },
  {
    id: "me-sundai-benesse-1",
    provider: "sundai",
    name: "ベネッセ・駿台マーク模試 第1回",
    aliases: ["ベネ駿マーク"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-13`,
    targetGrades: ["h3"],
    format: "mark",
  },
  {
    id: "me-sundai-benesse-kj",
    provider: "sundai",
    name: "ベネッセ・駿台記述模試",
    aliases: ["ベネ駿記述"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-10-19`,
    targetGrades: ["h3"],
    format: "descriptive",
  },

  // ─── 東進 ───
  {
    id: "me-toshin-kyotsu-1",
    provider: "toshin",
    name: "全国統一高校生テスト（春）",
    kana: "ぜんこくとういつこうこうせいてすと",
    aliases: ["全統テ"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-06-08`,
    targetGrades: ["h1", "h2", "h3"],
    format: "common-test-trial",
    officialUrl: "https://www.toshin.com/zentoitsu/",
  },
  {
    id: "me-toshin-kyotsu-2",
    provider: "toshin",
    name: "全国統一高校生テスト（秋）",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-11-02`,
    targetGrades: ["h1", "h2", "h3"],
    format: "common-test-trial",
    officialUrl: "https://www.toshin.com/zentoitsu/",
  },
  {
    id: "me-toshin-todai",
    provider: "toshin",
    name: "東大本番レベル模試",
    aliases: ["東進東大本レベ"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-13`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-tokyo"],
    officialUrl: "https://www.toshin.com/hr_moshi/",
  },
  {
    id: "me-toshin-kyodai",
    provider: "toshin",
    name: "京大本番レベル模試",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-08-03`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-kyoto"],
    officialUrl: "https://www.toshin.com/hr_moshi/",
  },
  {
    id: "me-toshin-kyotsu-honban",
    provider: "toshin",
    name: "共通テスト本番レベル模試",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-04-27`,
    targetGrades: ["h3", "ronin"],
    format: "common-test-trial",
    officialUrl: "https://www.toshin.com/hr_moshi/",
  },

  // ─── 代ゼミ ───
  {
    id: "me-yozemi-kyotsu",
    provider: "yozemi",
    name: "大学入学共通テスト入試プレ",
    kana: "だいがくにゅうがくきょうつうてすとにゅうしぷれ",
    aliases: ["代ゼミプレ"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-11-23`,
    targetGrades: ["h3", "ronin"],
    format: "common-test-trial",
    officialUrl: "https://www.yozemi.ac.jp/exam/moshi/",
  },
  {
    id: "me-yozemi-todai",
    provider: "yozemi",
    name: "東大入試プレ",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-11-09`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-tokyo"],
    officialUrl: "https://www.yozemi.ac.jp/exam/moshi/",
  },
  {
    id: "me-yozemi-kyodai",
    provider: "yozemi",
    name: "京大入試プレ",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-11-16`,
    targetGrades: ["h3", "ronin"],
    format: "univ-specific",
    targetUniversityIds: ["u-kyoto"],
    officialUrl: "https://www.yozemi.ac.jp/exam/moshi/",
  },

  // ─── ベネッセ・進研模試 ───
  {
    id: "me-benesse-shinken-h1-1",
    provider: "benesse",
    name: "進研模試（高1・7月）",
    kana: "しんけんもしこういちしちがつ",
    aliases: ["進研模試"],
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-12`,
    targetGrades: ["h1"],
    format: "mark-descriptive",
    notes: "学校実施型・申込は学校経由",
  },
  {
    id: "me-benesse-shinken-h2-1",
    provider: "benesse",
    name: "進研模試（高2・7月）",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-12`,
    targetGrades: ["h2"],
    format: "mark-descriptive",
  },
  {
    id: "me-benesse-shinken-h3-1",
    provider: "benesse",
    name: "進研模試 総合学力テスト（高3・7月）",
    year: CURRENT_YEAR,
    examDate: `${CURRENT_YEAR}-07-12`,
    targetGrades: ["h3"],
    format: "mark-descriptive",
  },
];

export const MOCK_EXAMS: MockExam[] = RAW.map((m) => {
  const enriched: MockExam = {
    ...m,
    source: m.source ?? "seed",
    searchText: undefined,
  };
  enriched.searchText = buildSearchText(enriched);
  return enriched;
});
